spring:
  application:
    name: coupon
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:coupon
    driver-class-name: org.h2.Driver
    username: sa
    password:

  redis:
    host: localhost
    port: 6379
    redisson:
      config: |
        singleServerConfig:
          address: "redis://localhost:6379"
          connectionMinimumIdleSize: 10
          connectionPoolSize: 64
          idleConnectionTimeout: 10000
        threads: 4
        nettyThreads: 4
